// Code generated by "stringer -type Kind -trimprefix Kind"; DO NOT EDIT.

package template

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KindLegacy-0]
	_ = x[KindIndex-1]
	_ = x[KindComponent-2]
}

const _Kind_name = "LegacyIndexComponent"

var _Kind_index = [...]uint8{0, 6, 11, 20}

func (i Kind) String() string {
	if i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
